_BASE_: "Base-SimpleBaseline.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SimpleBaseline:
    NUM_QUERIES: 100
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (220000,)
  MAX_ITER: 280000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
